# Generated by Django 5.2.6 on 2025-10-13 18:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monografia',
            options={'permissions': [('can_delete_monografia', 'Pode deletar monografia')], 'verbose_name': 'Monografia', 'verbose_name_plural': 'Monografias'},
        ),
        migrations.AddField(
            model_name='monografia',
            name='arquivo_documento',
            field=models.FileField(blank=True, null=True, upload_to='monografias/', verbose_name='Documento (PDF)'),
        ),
        migrations.CreateModel(
            name='HistoricalMonografia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('resumo', models.TextField()),
                ('abstract', models.TextField()),
                ('palavras_chave', models.CharField(help_text='Separadas por vírgula', max_length=255, verbose_name='Palavras-Chave')),
                ('arquivo_documento', models.TextField(blank=True, max_length=100, null=True, verbose_name='Documento (PDF)')),
                ('status', models.CharField(choices=[('AND', 'Em Andamento'), ('CON', 'Concluída para Defesa'), ('APR', 'Aprovada'), ('REP', 'Reprovada')], default='AND', max_length=3)),
                ('data_publicacao', models.DateField(blank=True, editable=False, verbose_name='Data de Publicação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aluno', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.aluno')),
                ('coorientador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.professor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('orientador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.professor')),
            ],
            options={
                'verbose_name': 'historical Monografia',
                'verbose_name_plural': 'historical Monografias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
