# Generated by ChatGPT on 2025-02-09

from django.db import migrations, models
from django.core.validators import FileExtensionValidator, MinValueValidator, MaxValueValidator
import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_monografia_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monografia",
            options={
                "ordering": ["-data_publicacao", "titulo"],
                "permissions": [
                    ("can_delete_monografia", "Pode deletar monografia")
                ],
                "verbose_name": "Monografia",
                "verbose_name_plural": "Monografias",
            },
        ),
        migrations.AddField(
            model_name="monografia",
            name="data_defesa",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[core.validators.validate_future_date],
                verbose_name="Data da Defesa",
            ),
        ),
        migrations.AlterField(
            model_name="banca",
            name="data_defesa",
            field=models.DateTimeField(
                validators=[core.validators.validate_future_date],
                verbose_name="Data e Hora da Defesa",
            ),
        ),
        migrations.AlterField(
            model_name="banca",
            name="nota_final",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                validators=[MinValueValidator(0), MaxValueValidator(100)],
                verbose_name="Nota Final",
            ),
        ),
        migrations.AlterField(
            model_name="monografia",
            name="arquivo_documento",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="monografias/",
                validators=[
                    FileExtensionValidator(["pdf"]),
                    core.validators.validate_pdf_extension,
                ],
                verbose_name="Documento (PDF)",
            ),
        ),
    ]
