# Generated by ChatGPT on 2025-02-09
from django.db import migrations, models
import core.validators
from django.core.validators import FileExtensionValidator, MinValueValidator, MaxValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_part1_hardening"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monografia",
            name="arquivo_documento",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="monografias/",
                validators=[FileExtensionValidator(["pdf"]), core.validators.validate_pdf_extension],
                verbose_name="Documento (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="banca",
            name="nota_final",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                validators=[MinValueValidator(0), MaxValueValidator(100)],
                verbose_name="Nota Final",
            ),
        ),
    ]
