# Generated by ChatGPT on 2025-02-09

from django.db import migrations, models
import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_api_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmonografia",
            name="data_defesa",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[core.validators.validate_future_date],
                verbose_name="Data da Defesa",
            ),
        ),
    ]
