# Generated by Django 5.2.6 on 2025-09-30 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Matrícula"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aluno_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulacao",
                    models.CharField(
                        choices=[
                            ("ME", "Mestre"),
                            ("DR", "Doutor"),
                            ("PD", "Pós-Doutor"),
                        ],
                        max_length=2,
                        verbose_name="Titulação",
                    ),
                ),
                (
                    "area_pesquisa",
                    models.CharField(max_length=255, verbose_name="Área de Pesquisa"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Professor",
                "verbose_name_plural": "Professores",
            },
        ),
        migrations.CreateModel(
            name="Monografia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("resumo", models.TextField()),
                ("abstract", models.TextField()),
                (
                    "palavras_chave",
                    models.CharField(
                        help_text="Separadas por vírgula",
                        max_length=255,
                        verbose_name="Palavras-Chave",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AND", "Em Andamento"),
                            ("CON", "Concluída para Defesa"),
                            ("APR", "Aprovada"),
                            ("REP", "Reprovada"),
                        ],
                        default="AND",
                        max_length=3,
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Publicação"
                    ),
                ),
                (
                    "aluno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monografia",
                        to="core.aluno",
                    ),
                ),
                (
                    "coorientador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monografias_coorientadas",
                        to="core.professor",
                    ),
                ),
                (
                    "orientador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monografias_orientadas",
                        to="core.professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monografia",
                "verbose_name_plural": "Monografias",
            },
        ),
        migrations.CreateModel(
            name="Banca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_defesa",
                    models.DateTimeField(verbose_name="Data e Hora da Defesa"),
                ),
                (
                    "local_defesa",
                    models.CharField(max_length=255, verbose_name="Local da Defesa"),
                ),
                (
                    "nota_final",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Nota Final",
                    ),
                ),
                (
                    "monografia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banca",
                        to="core.monografia",
                    ),
                ),
                (
                    "avaliadores",
                    models.ManyToManyField(
                        related_name="bancas_avaliadas", to="core.professor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Banca",
                "verbose_name_plural": "Bancas",
            },
        ),
    ]
